"""
Join parameter_maps/roi_stats.csv with patients/rat-grouping.csv to attach
each ROI's rat Group and Test End point — run with:
    uv run python join_roi_stats_grouping.py

roi_stats.csv's ``study_name`` is keyed by rat number (e.g. "693431", or
"Rat Spine 690066" for a few older studies with a name prefix); the numeric
rat number is extracted from it and matched against rat-grouping.csv's own
"Rat Number" column.

rat-grouping.csv has one row per (rat, disc) — Group/Test End point are only
filled in on a rat's first row, so they're forward-filled per rat before the
join. (Verified: every rat's Group/Test End point is constant across its
rows — forward-fill never has to reconcile a conflict.)

Writes parameter_maps/roi_stats_with_grouping.csv (roi_stats.csv itself is
left untouched, since it's regenerated by analyze_disc.py's upsert).
"""

import re
from pathlib import Path

import pandas as pd

ROI_STATS_PATH = Path("parameter_maps/roi_stats.csv")
GROUPING_PATH = Path("patients/rat-grouping.csv")
OUT_PATH = Path("parameter_maps/roi_stats_with_grouping.csv")


def _extract_rat_number(study_name: str) -> str:
    """Pull the numeric rat number out of a study_name like 'Rat Spine 690066' or '693431'."""
    m = re.search(r"\d+", str(study_name))
    if not m:
        raise ValueError(f"No rat number found in study_name: {study_name!r}")
    return m.group()


def main() -> None:
    stats = pd.read_csv(ROI_STATS_PATH).dropna(subset=["study_name"])
    stats["rat_number"] = stats["study_name"].map(_extract_rat_number)

    grouping = pd.read_csv(GROUPING_PATH, encoding="utf-8-sig")
    grouping["Rat Number"] = grouping["Rat Number"].ffill()
    grouping["Rat Number"] = grouping["Rat Number"].astype(int).astype(str)
    rat_info = grouping[["Rat Number", "Group", "Test End point"]].drop_duplicates(
        subset="Rat Number"
    )

    merged = stats.merge(
        rat_info, how="left", left_on="rat_number", right_on="Rat Number"
    )
    missing = merged[merged["Rat Number"].isna()]["rat_number"].unique()
    if len(missing):
        print(f"WARNING: no grouping entry found for rat number(s): {sorted(missing)}")

    merged = merged.drop(columns=["Rat Number"]).rename(
        columns={"Group": "group", "Test End point": "test_end_point"}
    )
    cols = list(merged.columns)
    cols.insert(cols.index("study_name") + 1, cols.pop(cols.index("rat_number")))
    merged = merged[cols]

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    merged.to_csv(OUT_PATH, index=False)
    print(f"Wrote {len(merged)} row(s) to {OUT_PATH}")


if __name__ == "__main__":
    main()
